### ISSUE TITLE
Release 3.0.0

### ISSUE THREAD

**Issue by jrbourbeau** [dask/zict#103]
@crusaderky is proposing we issue a new `zict` release (xref https://github.com/dask/zict/pull/100). I'm fine with this. @crusaderky you mentioned that this should be a major release, could you briefly mention any major changes? Are there breaking changes we should be aware of? 

cc @quasiben as I think `zict` is used in `dask-cuda`. It would be good to test against the `main` branch here (if you haven't already)

If there aren't any objections to a new release, I'll propose we push out a new release tomorrow

**Comment by crusaderky** [comment]
- The library is now almost completely thread-safe
- Dropped support for Python 3.7
- A ton of minor changes:  https://github.com/dask/zict/blob/main/doc/source/changelog.rst#230---unreleased

There are no breaking changes other than the minimum Python version.

**Comment by quasiben** [comment]
Thanks for the pin @jrbourbeau .

After doing the necessary update in https://github.com/rapidsai/dask-cuda/pull/1160, one of the Dask-CUDA tests where we verify that the spilled files listed in zict.File.keys(), the last chunk in that list seems to be always missing.   If we have keys operation-name-UUID#0 through operation-name-UUID#10, this last one is not on disk when we try to read it.
The failure happens [in this block](https://github.com/rapidsai/dask-cuda/blob/590d26ab4d61b785789ee6bacae29c37337e6703/dask_cuda/tests/test_spill.py#L32-L36), where we assemble the path for the spilled chunks and when we ultimately read it with os.path.getsize(f) we ultimately find that the file for the last chunk is missing.

Are we missing anything obvious ?

As for moving forward short-term we'll either pin/xfail/fix on our end (again attempting to fix  in #1160).  If we do end up pinning to an older zict will that be a problem in Distributed ?  As in, will Distributed be requiring an upgraded zict version ?

**Comment by crusaderky** [comment]
@quasiben the file names for `File` have changed from `<path>/<safe key>` to `<path>/<safe key>#<ever-increasing integer>`. This was to avoid race conditions when a key is deleted and re-inserted.

Have a look at our test code:
https://github.com/dask/distributed/blob/600b99386af37592713853eb94e9956b23490a76/distributed/tests/test_spill.py#L22-L30

**Comment by pentschev** [comment]
I checked the fix @crusaderky locally and the test now succeeds with it. I think from Dask-CUDA we're good for zict 3.0.

**Comment by quasiben** [comment]
Thanks @crusaderky for the helpful comments.  +1 for releasing

**Comment by jrbourbeau** [comment]
Great, thanks for confirming @quasiben @pentschev. Will push out a release in a few minutes

**Comment by jrbourbeau** [comment]
`zict=3.0.0` is out on PyPI and the conda-forge PR is open https://github.com/conda-forge/zict-feedstock/pull/15
