### ISSUE TITLE
File.__contains__ is slow

### ISSUE THREAD

**Issue by mrocklin** [dask/zict#12]
It is convenient in Dask to frequently check if a key is present in the `.data` dictionary.  Unfortunately this is slow, due to calls to both `os.path.exists` and `_safe_key`.

**Comment by pitrou** [comment]
Since those mapping classes are not meant for persisting data accross processes, it would be possible to have an internal key cache. Keys are already stored somewhere else (presumably?), so perhaps this wouldn't increase memory consumption too much.

**Comment by mrocklin** [comment]
I'm curious now about how `_safe_key` interacts with the `keys()` method.  It's tricky to reverse that function when finding keys from filenames for an existing directory.

**Comment by pitrou** [comment]
You're right, it seems `keys()` and `__iter__` are incorrect.

**Comment by pitrou** [comment]
Speaking of which, the `mode` argument to `File` has never been used. What was the original intent?

**Comment by mrocklin** [comment]
Presumably to optionally support read-only?
