### ISSUE TITLE
Set repository homepage to zict.readthedocs.io?

### ISSUE THREAD

**Issue by hartwork** [dask/zict#17]
Hi!

It would b cool to not having to Google for this:
http://zict.readthedocs.io/en/latest/

Thanks, Sebastian

**Comment by mrocklin** [comment]
Thanks for the error report.  This should now be fixed.  If you can think of other places to put these links then please say so.

**Comment by hartwork** [comment]
Cool that you're in with this. I was originally referring to the homepage field of the https://github.com/dask/zict repository, e.g. as seen with https://github.com/libexpat/libexpat. So that option is still open :)

**Comment by mrocklin** [comment]
Done

On Wed, Jun 28, 2017 at 9:59 AM, Sebastian Pipping <notifications@github.com

**Comment by hartwork** [comment]
Nice :)
