### ISSUE TITLE
Memory issues related to Pandas series

### ISSUE THREAD

**Issue by bluenote10** [dask/zict#19]
I found something interesting related to https://github.com/dask/distributed/issues/1015. I wrote a small test, which replicates how the Distributed workers use the zict buffers. The test sets an artificially low memory limit and fills the buffer with DataFrames or Series:

```python
from __future__ import division, print_function

import pandas as pd
import os
import gc
import psutil
import tempfile

from zict import Buffer, File, Func

# To replicate usage in Distributed workers
from distributed.protocol import deserialize_bytes, serialize_bytelist
from distributed.sizeof import safe_sizeof as sizeof


def get_mem_usage():
    process = psutil.Process(os.getpid())
    mem_usage = process.memory_info().rss / float(2 ** 20)
    return mem_usage


def weight(k, v):
    return sizeof(v)


def gen_df(n=10000000):
    return pd.DataFrame({"A": [0] * n})


def run_test(store_df=True, store_series=True, explicit_collect=False):
    memory_limit = 1
    local_dir = tempfile.mkdtemp(prefix='worker-', dir=".")

    path = os.path.join(local_dir, 'storage')
    storage = Func(serialize_bytelist, deserialize_bytes, File(path))
    data = Buffer({}, storage, int(float(memory_limit)), weight)

    # simulate filling LRU with data
    for iteration in xrange(30):
        df = gen_df()

        if store_df:
            key = "key_{}".format(iteration)
            data[key] = df

        if store_series:
            for c in df.columns:
                key = "key_{}_{}".format(iteration, c)
                data[key] = df[c]
            del c

        del df

        if explicit_collect:
            gc.collect()

        print("Iteration: {:2d}    Mem: {:12.1f} MB    data.fast = {}".format(
            iteration, get_mem_usage(), data.fast
        ))

run_test()
```

When running with `store_series=False` the memory usage stays pretty much stable at < 60 MB. Apparently the LRU works fine and the garbage collector triggers properly. However, when storing the series as well, the behavior changes to:

```
Iteration:  0    Mem:        391.8 MB    data.fast = <LRU: 0/1 on dict>
Iteration:  1    Mem:        728.1 MB    data.fast = <LRU: 0/1 on dict>
Iteration:  2    Mem:       1062.4 MB    data.fast = <LRU: 0/1 on dict>
Iteration:  3    Mem:       1394.8 MB    data.fast = <LRU: 0/1 on dict>
Iteration:  4    Mem:       1729.1 MB    data.fast = <LRU: 0/1 on dict>
Iteration:  5    Mem:       2063.4 MB    data.fast = <LRU: 0/1 on dict>
Iteration:  6    Mem:        401.9 MB    data.fast = <LRU: 0/1 on dict>
Iteration:  7    Mem:        734.2 MB    data.fast = <LRU: 0/1 on dict>
Iteration:  8    Mem:       1066.5 MB    data.fast = <LRU: 0/1 on dict>
Iteration:  9    Mem:       1398.8 MB    data.fast = <LRU: 0/1 on dict>
Iteration: 10    Mem:       1731.1 MB    data.fast = <LRU: 0/1 on dict>
Iteration: 11    Mem:       2063.4 MB    data.fast = <LRU: 0/1 on dict>
Iteration: 12    Mem:       2397.7 MB    data.fast = <LRU: 0/1 on dict>
Iteration: 13    Mem:       2732.0 MB    data.fast = <LRU: 0/1 on dict>
Iteration: 14    Mem:       3066.3 MB    data.fast = <LRU: 0/1 on dict>
Iteration: 15    Mem:       3400.7 MB    data.fast = <LRU: 0/1 on dict>
Iteration: 16    Mem:       3735.0 MB    data.fast = <LRU: 0/1 on dict>
Iteration: 17    Mem:       4069.3 MB    data.fast = <LRU: 0/1 on dict>
Iteration: 18    Mem:       4403.6 MB    data.fast = <LRU: 0/1 on dict>
Iteration: 19    Mem:       4737.9 MB    data.fast = <LRU: 0/1 on dict>
Iteration: 20    Mem:       5072.2 MB    data.fast = <LRU: 0/1 on dict>
Iteration: 21    Mem:       5406.5 MB    data.fast = <LRU: 0/1 on dict>
Iteration: 22    Mem:       5740.8 MB    data.fast = <LRU: 0/1 on dict>
Iteration: 23    Mem:       6075.1 MB    data.fast = <LRU: 0/1 on dict>
Iteration: 24    Mem:       6409.4 MB    data.fast = <LRU: 0/1 on dict>
Iteration: 25    Mem:       6743.7 MB    data.fast = <LRU: 0/1 on dict>
Iteration: 26    Mem:       7077.6 MB    data.fast = <LRU: 0/1 on dict>
zsh: killed     ./debug_zict.py
```

Apparently the garbage collector has a problem with this situation. It seems to clean the memory once at around the 2 GB mark, but after that it won't trigger automatically at all, and the process goes out-of-memory. This would explain the issues observed in the Distributed workers. Note: The problem occurs with both glibc and jemalloc.

I don't think this is a true memory leak, because the problem can be solved by enabling the explicit garbage collection, which brings the memory usage back to a constant < 60 MB.

This raises two questions:

* Do you have any idea why storing `pandas.Series` would throw off the garbage collector? Is this a result of the way the zict buffer works, or rather a Pandas problem?
* Considering that explicit garbage collection is a viable work-around: Would you mind having an explicit `gc.collect()` somewhere in either zinc's `fast_to_slow` or in the Distributed workers? It would probably make sense even without the weird GC issue to minimize heap fragmentation.

**Comment by mrocklin** [comment]
First, thank you so much for tracking this down.  This seems like an important issue and not something that was at all obvious to me. 

Lets cc @jreback in case he knows of reasons why pandas Series and DataFrames might differ here and @pitrou in case he knows of reasons why the garbage collector would not be triggered.  

I think it would be reasonable to call `gc.collect` in `fast_to_slow` if it hasn't been called already in the last second or so.

**Comment by jreback** [comment]
```
        if store_series:
            for c in df.columns:
                key = "key_{}_{}".format(iteration, c)
                data[key] = df[c]
            del c
```

``del c`` does nothing; c is a string. 

therefore you are keeping a reference to the underlying data around.

``df[c]`` simply creates a Series which contains a view of a numpy array. So you are accumulating things.

**Comment by jreback** [comment]
original
```
In [8]: for iteration in range(30):
   ...:       df = gen_df()
   ...:       for c in df.columns:
   ...:           key = "key_{}_{}".format(iteration, c)
   ...:           data[key] = df[c]
   ...:       del c
   ...:       del df
   ...:       print("Iteration: {:2d}    Mem: {:12.1f} MB".format(
   ...:             iteration, get_mem_usage()
   ...:       ))
   ...:       
Iteration:  0    Mem:        181.3 MB
Iteration:  1    Mem:        257.6 MB
Iteration:  2    Mem:        333.9 MB
Iteration:  3    Mem:        410.2 MB
Iteration:  4    Mem:        486.5 MB
Iteration:  5    Mem:        562.8 MB
Iteration:  6    Mem:        639.1 MB
Iteration:  7    Mem:        715.4 MB
Iteration:  8    Mem:        791.7 MB
Iteration:  9    Mem:        868.0 MB
Iteration: 10    Mem:        944.3 MB
Iteration: 11    Mem:       1020.6 MB
Iteration: 12    Mem:       1096.9 MB
Iteration: 13    Mem:       1173.1 MB
Iteration: 14    Mem:       1249.4 MB
```

use this
```
In [12]: for iteration in range(30):
    ...:       df = gen_df()
    ...:       for c in df.columns:
    ...:           key = "key_{}_{}".format(iteration, c)
    ...:           data[key] = df.pop(c)
    ...:       del c
    ...:       del df
    ...:       print("Iteration: {:2d}    Mem: {:12.1f} MB".format(
    ...:             iteration, get_mem_usage()
    ...:       ))
    ...:       

Iteration:  0    Mem:       1250.8 MB
Iteration:  1    Mem:       1250.8 MB
Iteration:  2    Mem:       1250.8 MB
Iteration:  3    Mem:       1250.8 MB
Iteration:  4    Mem:       1250.8 MB
````

IOW you need to separate the Series from the df.

**Comment by bluenote10** [comment]
I'm confused: The call `data[key] = df[c]` writes `df[c]` straight to disk and there is no reference to `df[c]` any more. But if that is what needs to be changed we would have to look on the Dask side again.

@mrocklin Having a closer look, `fast_to_slow` is probably not the right place for the `collect` because `value` is still referenced by the caller. In fact, the example above goes straight into [this call to the slow storage](https://github.com/dask/zict/blob/71d5bd6cf6677d4b01aff66fed6eebb9a96e4621/zict/buffer.py#L82). So maybe better to trigger the collect on call-site (Dask worker) allowing to run `del value` before the collect?

The most reasonable place in zict would maybe be [here](https://github.com/dask/zict/blob/71d5bd6cf6677d4b01aff66fed6eebb9a96e4621/zict/file.py#L86), because the write to disk is slow anyway. But this would always leave 1 copy of the data in memory, i.e., the memory usage in the example above would be a constant ~380 MB, never getting rid of the `value` reference from `__setitem__`.

**Comment by bluenote10** [comment]
How can we proceed with this issue?

@jreback Would you agree that writing `df[c]` to file and not storing references should work in general?

If there aren't any other ideas I would prepare a PR on the Distributed worker side which performs the explicit GC.

**Comment by jreback** [comment]
> @jreback Would you agree that writing df[c] to file and not storing references should work in general?

yes that sounds reasonable

**Comment by jakirkham** [comment]
I wonder how much of an issue this still is after adding pickle protocol 5 support ( https://github.com/dask/distributed/pull/3784 ) ( https://github.com/dask/distributed/pull/3849 ). This avoids the `memcpy`s that would otherwise happen with older pickle protocols by using zero-copy. Distributed + Zict already know how to handle the multiple buffers that would be generated from this procedure efficiently

**Comment by pitrou** [comment]
@jakirkham Out of curiosity, were any benchmarks run after the switch to protocol 5?

**Comment by jakirkham** [comment]
I think we may have done some microbenchmarks. Can try to dig that up

More generally we have been benchmarking the Scheduler and have already gone and rewritten serialization to more optimally leverage MsgPack. There might be a little bit more juice there, but not really related to Pandas or Pickle specifically. Overhead from Tornado and TCP is a bigger issue. There’s also some more to do in the Scheduler.

I know this last bit isn’t exactly answering your question, but hopefully it gives a sense of relative effect (IOW pickle protocol 5 is fast enough that other things are the bottlenecks)

**Comment by jakirkham** [comment]
So tried rerunning OP's code. Wasn't able to use exactly as it had `xrange` (changed to `range`). Am using Python 3.8. This is what I get after several iterations:

<details>
```
Iteration:  0    Mem:        487.5 MB    data.fast = <LRU: 0/1 on dict>
Iteration:  1    Mem:        497.2 MB    data.fast = <LRU: 0/1 on dict>
Iteration:  2    Mem:        497.1 MB    data.fast = <LRU: 0/1 on dict>
Iteration:  3    Mem:        497.1 MB    data.fast = <LRU: 0/1 on dict>
Iteration:  4    Mem:        344.9 MB    data.fast = <LRU: 0/1 on dict>
Iteration:  5    Mem:        420.8 MB    data.fast = <LRU: 0/1 on dict>
Iteration:  6    Mem:        344.7 MB    data.fast = <LRU: 0/1 on dict>
Iteration:  7    Mem:        497.3 MB    data.fast = <LRU: 0/1 on dict>
Iteration:  8    Mem:        497.2 MB    data.fast = <LRU: 0/1 on dict>
Iteration:  9    Mem:        497.0 MB    data.fast = <LRU: 0/1 on dict>
Iteration: 10    Mem:        420.9 MB    data.fast = <LRU: 0/1 on dict>
Iteration: 11    Mem:        497.2 MB    data.fast = <LRU: 0/1 on dict>
Iteration: 12    Mem:        344.9 MB    data.fast = <LRU: 0/1 on dict>
Iteration: 13    Mem:        420.9 MB    data.fast = <LRU: 0/1 on dict>
Iteration: 14    Mem:        497.1 MB    data.fast = <LRU: 0/1 on dict>
Iteration: 15    Mem:        344.8 MB    data.fast = <LRU: 0/1 on dict>
Iteration: 16    Mem:        497.1 MB    data.fast = <LRU: 0/1 on dict>
Iteration: 17    Mem:        497.1 MB    data.fast = <LRU: 0/1 on dict>
Iteration: 18    Mem:        344.9 MB    data.fast = <LRU: 0/1 on dict>
Iteration: 19    Mem:        497.1 MB    data.fast = <LRU: 0/1 on dict>
Iteration: 20    Mem:        497.3 MB    data.fast = <LRU: 0/1 on dict>
Iteration: 21    Mem:        497.1 MB    data.fast = <LRU: 0/1 on dict>
Iteration: 22    Mem:        497.1 MB    data.fast = <LRU: 0/1 on dict>
Iteration: 23    Mem:        497.1 MB    data.fast = <LRU: 0/1 on dict>
Iteration: 24    Mem:        344.9 MB    data.fast = <LRU: 0/1 on dict>
Iteration: 25    Mem:        420.9 MB    data.fast = <LRU: 0/1 on dict>
Iteration: 26    Mem:        497.2 MB    data.fast = <LRU: 0/1 on dict>
```
</details>

There is some fluctuation in memory usage (actually towards the lower end interestingly). That said, it seems to stay stable and not really grow (as was originally seen). Given this, it appears this issue has since been resolved (likely due to `pickle5` support though possibly other things as well). Going to go ahead and close. Feel free to open a new issue if other problems crop up. Thanks!
