### ISSUE TITLE
A sqlite-backed MutableMapping

### ISSUE THREAD

**Issue by danielballan** [dask/zict#24]
Would zict be interested in merging a sqlite-backed dict, which I currently maintain as a small standalone repo, [historydict](https://github.com/Nikea/historydict)?

**Comment by mrocklin** [comment]
In general I don't see any issue with adding a SQLite dict.  Some thoughts:

1.  What are your thoughts on the extra functionality like `.past` and turning keys into strings?  This is slightly above and beyond the normal MutableMapping protocol.  I'm curious how zict should handle extra features like this in the future.
2.  Is it better to bring many mutablemapping projects under the same umbrella project, or is it better to keep them separate?

**Comment by danielballan** [comment]
(We covered this in person, but I'll post for anyone else following along.)

1. I think `.past` is probably best left out of scope for `zict`, for the sake of maintaining a clear and straightforward scope. I imagine that I would continue to maintain HistoryDict. Zict's `File` only allows string-typed keys, and I think it would be reasonable to do the same for a sqlite variety, to start.
2. My first thought is that zict is an umbrella is good for discoverability. My main concern would be bringing in extra dependencies. Of course that's not an issue in the case of sqlite.

**Comment by mrocklin** [comment]
Seems fine to me

**Comment by martindurant** [comment]
@danielballan , has this been implemented?

**Comment by jakirkham** [comment]
There's an [`SQLiteStore` in Zarr]( https://zarr.readthedocs.io/en/stable/api/storage.html#zarr.storage.SQLiteStore )

**Comment by danielballan** [comment]
Oops, sorry I missed your comment a year and a half ago @martindurant. I learned that SQLite plays badly with NFS and had to take a different approach for my use case. Thanks for the update @jakirkham. I’ll close this.
