### ISSUE TITLE
heapdict will break in Python 3.8

### ISSUE THREAD

**Issue by gimperiale** [dask/zict#26]
When importing distributed, Python 3.7 emits the following:

heapdict.py:11: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
class heapdict(collections.MutableMapping):

[Looking at the project page](https://github.com/DanielStutzbach/heapdict), the last commit is from 2012 and no issues raised since 2014 have ever been replied to.
It may be a good idea to just copy-paste the heapdict implementation into zict and remove the external dependency.

**Comment by TomAugspurger** [comment]
Thanks. Agreed that an upstream fix doesn't look likely.

**Comment by tacaswell** [comment]
I have talked with the author of heapdict, I think a new release is likely.

**Comment by TomAugspurger** [comment]
Good to know, thanks.

Python 3.8 is scheduled for October 21. We can do a zict release just
before then if needed.

**Comment by tacaswell** [comment]
@DanielStutzbach just released a new version of heapdict.  Probably should bump up the minimum version on zict?

**Comment by TomAugspurger** [comment]
Thanks @DanielStutzbach and @tacaswell!

I think we're probably OK here. I don't expect zict requiring heapdict >= 1.1 (possibly for python 3.8 only) to fix any problems in practice. If someone is installing zict on 3.8, they're probably getting the latest heapdict anyway.
