### ISSUE TITLE
LRU mapping not `KeyboardInterrupt` resilient

### ISSUE THREAD

**Issue by jrbourbeau** [dask/zict#29]
I've had users report `zict.LRU` not being able to recover from `KeyboardInterrupt`s. This is because the `__setitem__` and `__delitem__` methods for the `LRU` mapping modify multiple other internal mappings (e.g. `LRU.d`, `LRU.heap`). So when a `KeyboardInterrupt` error is raised while one of these methods are executing, it's possible that not all of the internal state will be updated (e.g. delete a key from `d` but not from `heap`) which can result in `KeyError`s and `IndexError`s when the `LRU` mapping is used later on (example below). 

I'd like to propose we wrap the current `__setitem__` / `__delitem__` in `try`/`except`s to catch `BaseException`s and restore the internal mappings to their original state if an error is caught. @mrocklin does this seem reasonable? 

### Example

The snippet below creates an `LRU` mapping and defines a function (`func`) which will add and remove items from the mapping. 

```python
import random
import zict

cache = zict.LRU(10, dict())

def func():
    # Add two items to the mapping
    cache[random.randrange(10)] = 0
    cache[random.randrange(10)] = 0
    # Delete one random item from the mapping
    del cache[random.choice(list(cache))]
```

Then let `func` run and raise a `KeyboardInterrupt` via ctrl-c:

```python
while True:
    func()
    # ctrl-c while this is running to raise `KeyboardInterrupt` error
```

Running `func()` again will raise a `KeyError` (note this may need to be repeated a few times):

```python
while True:
    func()
```

<details>
<summary>Error output:</summary>

```python
In [8]: while True:
   ...:     func()
   ...:
^C---------------------------------------------------------------------------
KeyboardInterrupt                         Traceback (most recent call last)
<ipython-input-8-4115c82518dc> in <module>
      1 while True:
----> 2     func()
      3

<ipython-input-6-5207866116f1> in func()
      7     # Add items to the mapping
      8     cache[random.randrange(10)] = 0
----> 9     cache[random.randrange(10)] = 0
     10     # Delete random item from the mapping
     11     del cache[random.choice(list(cache))]

~/github/dask/zict/zict/lru.py in __setitem__(self, key, value)
     62             self.heap[key] = self.i
     63
---> 64             self.weights[key] = weight
     65             self.total_weight += weight
     66         else:

KeyboardInterrupt:

In [9]: while True:
   ...:     func()
   ...:
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-9-4115c82518dc> in <module>
      1 while True:
----> 2     func()
      3

<ipython-input-6-5207866116f1> in func()
      7     # Add items to the mapping
      8     cache[random.randrange(10)] = 0
----> 9     cache[random.randrange(10)] = 0
     10     # Delete random item from the mapping
     11     del cache[random.choice(list(cache))]

~/github/dask/zict/zict/lru.py in __setitem__(self, key, value)
     53     def __setitem__(self, key, value):
     54         if key in self.d:
---> 55             del self[key]
     56
     57         weight = self.weight(key, value)

~/github/dask/zict/zict/lru.py in __delitem__(self, key)
     94         del self.d[key]
     95         del self.heap[key]
---> 96         self.total_weight -= self.weights.pop(key)
     97
     98     def keys(self):

KeyError: 0
```

</details>

**Comment by mrocklin** [comment]
Assuming that it doesn't affect the common case much in either performance or code complexity I'm in favor of it.  I wouldn't be surprised if it gets somewhat complex though, at which point it might become an interesting judgement call.

**Comment by jrbourbeau** [comment]
> I wouldn't be surprised if it gets somewhat complex though

So things did indeed get complex (adding a `try`/`except` to undo the action of `__setitem__`, `__delitem__`, and `evict` when a `BaseExceptions` is raised). Additionally, to make everything fully robust to `KeyboardInterrupt`s would require a similar set of changes to `heapdict`.

I was hoping to fix this edge case upstream in `zict` so other projects using `LRU` might also benefit. But given the increase in code complexity and general maintenance burden, we (and `heapdict` maintainers) may not want to accept these changes unless this `KeyboardInterrupt` issue becomes a more widespread user problem.

For context, the particular use case I'm interested in is `distributed`'s used of `zict.LRU` as a cache for function serialization:

https://github.com/dask/distributed/blob/35551998d7350cd5ae6a5c24970d8437fd8d521d/distributed/worker.py#L3190-L3209

What do you think about using `functools.lru_cache` there instead of `zict.LRU`? For reference, what currently use `functools.lru_cache` for function *de*serialization caching:

https://github.com/dask/distributed/blob/35551998d7350cd5ae6a5c24970d8437fd8d521d/distributed/worker.py#L3150-L3152

**Comment by mrocklin** [comment]
I think that the reason we used our own LRU implementation is that we needed to weight the values.  We don't want the last 100 elements, we want the last 100GB of data (for example)

**Comment by jrbourbeau** [comment]
IIUC the original issue (xref https://github.com/dask/distributed/issues/2621) which prompted the use of `zict.LRU` for the cache was to put some kind of limit on the size of the cache (before we were using a `dict` which could grow indefinitely). As you mentioned, using `functools.lru_cache` would limit the cache in terms of the total number of serialized functions instead of the total number of bytes in the cache. 

If it's important in practice to have a hard limit on the bytes stored in the cache, then our current use of `zict.LRU` is the way to go. If the goal is to not allow the cache to grow indefinitely, then I have a slight preference for `functools.lru_cache` as it avoid this (albeit probably pretty rare) edge case where the `LRU` cache can go into an unfavorable state. Do you think switching to `functools.lru_cache` would have negative impact on users today?

**Comment by mrocklin** [comment]
Oh sorry, I didn't read that closely enough.  yeah, I think it'd be ok to use `functools.lru_cache` there.

**Comment by jrbourbeau** [comment]
I'm going to close this issue as we ended up addressing the specific use of `LRU` I was concerned with over in https://github.com/dask/distributed/pull/3260. Thanks for the feedback here @mrocklin
