### ISSUE TITLE
Importing ABC directly from collections is deprecated and removed in Python 3.9 

### ISSUE THREAD

**Issue by tirkarthi** [dask/zict#30]
Importing ABC directly from collections is deprecated and removed in Python 3.9 

https://bugzilla.redhat.com/show_bug.cgi?id=1793163

https://github.com/dask/zict/blob/30300fc0ad44eb8a357748d99cb541a2d5c9efa8/zict/tests/utils_test.py#L3

https://github.com/dask/zict/blob/30300fc0ad44eb8a357748d99cb541a2d5c9efa8/zict/tests/test_zip.py#L1

**Comment by tirkarthi** [comment]
I will add a PR for this.

**Comment by jrbourbeau** [comment]
Thanks @tirkarthi!
