### ISSUE TITLE
Release?

### ISSUE THREAD

**Issue by jakirkham** [dask/zict#37]
Would like to make a new release to get a lot of the recent fixes out there.

It appears we dropped Python 2. Not sure whether we consider that a breaking change. Other changes appear to be bug fixes (though correct me if I'm wrong).

Not sure where that leaves us for version number. Could see anything from 1.0.1 or 1.1.0 to 2.0.0 depending. Thoughts?

**Comment by jrbourbeau** [comment]
A new release sounds good to me, thanks for bringing it up @jakirkham! Either a minor (1.1.0) or major (2.0.0) version number bump seems reasonable -- no strong opinion from me. @mrocklin when you get a chance could you please add me as a maintainer on PyPI

**Comment by mrocklin** [comment]
Done.

**Comment by jakirkham** [comment]
Maybe we should go with 2.0.0. PR ( https://github.com/dask/zict/pull/36 ) could break stored `zict`s (though this may not be the common case), which would be good to communicate to users as well by making a major release.

**Comment by jrbourbeau** [comment]
Thanks @mrocklin! 

> Maybe we should go with 2.0.0

Sounds good to me. If there aren't any objections, I'll plan to merge #35 and then do a 2.0.0 release later this afternoon

**Comment by jakirkham** [comment]
SGTM. Thanks for managing this @jrbourbeau! Please let us know if you need help 🙂
