### ISSUE TITLE
Error: No module named 'zict'

### ISSUE THREAD

**Issue by nagesh4193** [dask/zict#42]
Team - I am trying to build a travis file with power support architecture. My travis is failing saying No module found for zict with doc/source/conf.py:68: in <module> import zict. Could someone please help to solve the issue?

https://travis-ci.com/github/nagesh4193/zict/jobs/479008204

**Environment**:

- Python version: 3.7, 3.8
- Operating System: Ubuntu 16.04
- arch: amd64, ppc64le

**Comment by jrbourbeau** [comment]
Thanks for raising an issue @nagesh4193. This seems like an issue with Travis CI instead of an issue with zict. I recommend reading through Travis CI's documentation and opening up and issue with them if you're still running into an issue.
