### ISSUE TITLE
Verify that Read the Docs is building after master -> main 

### ISSUE THREAD

**Issue by jsignell** [dask/zict#44]
Spotted on https://github.com/dask/dask-cloudprovider/issues/244#issuecomment-795310925. Read The Docs was still building `latest` from the `master` branch and builds were failing. It was configured to build from the default branch, but had cached the value `master` somewhere. Manually pointing it to  `main` in the RtD control panel fixed things.

**Comment by jrbourbeau** [comment]
@mrocklin could you add me to RTD (when you're back online)

**Comment by jakirkham** [comment]
Were we able to recheck this? I think I only have access to Dask on RTD. So am unable to check myself

**Comment by jrbourbeau** [comment]
I just moved RTD to build from `main` and kicked off a fresh build. Will close after that build succeeds
