### ISSUE TITLE
`File`'s `mode` unused

### ISSUE THREAD

**Issue by jakirkham** [dask/zict#52]
Currently `File` takes [a `mode` parameter]( https://github.com/dask/zict/blob/5060570f80df9ff854c1fb22138982e2f7ff4c36/zict/file.py#L53 ), but AFAICT it is unused. Is this suppose to be doing something?

**Comment by jakirkham** [comment]
For example if `mode="w"` should we be deleting the directory and recreating it?

**Comment by jrbourbeau** [comment]
Yeah, I'm not sure it's ever been used. Here's the commit where `File` was added https://github.com/dask/zict/commit/1902851997d4c5f33d8de36c250f98ae7462beff and `File.mode` doesn't appear to be used at that point either. I'm inclined to remove the `mode=` parameter (with a short deprecation cycle). Thoughts?

**Comment by jakirkham** [comment]
Interesting, thanks for git sleuthing 🙂

I wonder if it was added to simply match things like `open` (IOW to make it an easier drop-in).

Anyways ok deprecating if we have no plan to support it (after all it is a no-op currently). If there is actual usage, this would also give us an idea of how it is used (via user feedback).

**Comment by crusaderky** [comment]
Closed in #74
