### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by jakirkham** [dask/zict#59]
Looks like there are quite a few changes in `main` already that are unreleased. Wondering if it makes sense to cut a new release.

Thoughts @dask/maintenance? 🙂

**Comment by jrbourbeau** [comment]
Yeah, it'd be good to get a `zict` release out. Some of the recent changes here impact `distributed`. @crusaderky mentioned we should release _after_ the next `distributed` release (xref https://github.com/dask/zict/pull/56#issuecomment-1046288845), which is tentatively scheduled for this Friday (xref https://github.com/dask/community/issues/226). I'm happy to handle releasing `zict` after `distributed` has been pushed out

**Comment by jakirkham** [comment]
SGTM. Thanks James! 😄

**Comment by jrbourbeau** [comment]
Closing as `zict=2.1.0` is out on PyPI and conda-forge

**Comment by jakirkham** [comment]
Thanks James! 😀
